return {
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   lazy = true,
  --   branch = "canary",
  --   keys = {
  --     {
  --       "<Leader>aa",
  --       ":'<,'>CopilotChat<CR>",
  --       mode = { "v" },
  --       desc = "Copilot Chat Selection",
  --     },
  --   },
  -- },
  -- {
  --   "folke/edgy.nvim",
  --   event = "VeryLazy",
  --   opts = {
  --     exit_when_last = false,
  --     animate = {
  --       enabled = false,
  --     },
  --     wo = {
  --       winbar = true,
  --       winfixwidth = true,
  --       winfixheight = false,
  --       winhighlight = "WinBar:EdgyWinBar,Normal:EdgyNormal",
  --       spell = false,
  --       signcolumn = "no",
  --     },
  --     right = {
  --       {
  --         ft = "copilot-chat",
  --         title = "Copilot",
  --         size = { width = 0.18 },
  --       },
  --     },
  --   },
  -- },
}
